### ISSUE TITLE
fsck.c:1053:18: error: ‘node’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

### ISSUE THREAD

**Issue by jameshilliard** [exfatprogs/exfatprogs#51] opened 2020-04-17 19:37 UTC
I'm seeing this build error when i attempt to compile exfatprogs.
```
fsck.c: In function ‘main’:
fsck.c:1053:18: error: ‘node’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     node->parent = dir;
                  ^
fsck.c:861:22: note: ‘node’ was declared here
  struct exfat_inode *node;
                      ^
fsck.c: At top level:
```

**Comment by namjaejeon** [comment] 2020-04-17 22:23
@jameshilliard Can you send the patch to fix it ?

**Comment by jameshilliard** [comment] 2020-04-17 22:31
@namjaejeon I attempted to write one but I'm not really sure how to fix this properly.

**Comment by hclee** [comment] 2020-04-17 22:51
> @namjaejeon I attempted to write one but I'm not really sure how to fix this properly.

it seems initializing the variable with NULL is enough.

**Comment by namjaejeon** [comment] 2020-04-20 06:12
@jameshilliard Could you please try to build with #exfat-next of exfatprogs ? We applied the patch to #exfat-next branch.

**Comment by namjaejeon** [comment] 2020-04-24 07:08
@jameshilliard We merged the patches in #exfat-next branch to master branch and released exfatprogs-1.0.2 version. Can you confirm if your build error is fixed ?

**Comment by jameshilliard** [comment] 2020-04-24 07:10
I'll go ahead and bump the buildroot package, the autobuilders should catch any additional build issues.

**Comment by jameshilliard** [comment] 2020-04-24 19:14
Looks like it's still failing [here](http://autobuild.buildroot.net/results/5c5/5c5d71fde80a4f2f027085bdb0fae9fb76ab9d32/build-end.log)

**Comment by namjaejeon** [comment] 2020-04-25 14:15
Hm.. If we can reproduce it, we can easily fix it... @hclee Hyunchul, any opinion ?

**Comment by jameshilliard** [comment] 2020-04-28 12:31
If you want to reproduce it using buildroot's buildsystem/toolchains do this:
```
git clone https://github.com/buildroot/buildroot.git
cd buildroot
wget http://autobuild.buildroot.net/results/5c5/5c5d71fde80a4f2f027085bdb0fae9fb76ab9d32/config
mv config .config
make
```
You might need to checkout [the specific buildroot commit the test failed on](http://autobuild.buildroot.net/results/5c5/5c5d71fde80a4f2f027085bdb0fae9fb76ab9d32/gitid) but it will probably reproduce fine on master.

To test the fix do this:
```
cd buildroot
echo "EXFATPROGS_OVERRIDE_SRCDIR = /home/exfatprogs" > local.mk
make
```

To clean the exfatprogs build during testing
```
cd buildroot
make exfatprogs-dirclean
```

**Comment by namjaejeon** [comment] 2020-04-29 12:52
@jameshilliard Thanks! Will try!

**Comment by namjaejeon** [comment] 2020-04-29 13:36
linkinjeon@linkinjeon-System-Product-Name:~/git/exfat_work/buildroot$ make

You seem to have the current working directory in your
LD_LIBRARY_PATH environment variable. This doesn't work.
support/dependencies/dependencies.mk:27: recipe for target 'dependencies' failed
make: *** [dependencies] Error 1

Help me!

**Comment by jameshilliard** [comment] 2020-04-29 16:02
Strange, I haven't seen that before, maybe make sure you have all packages [here](https://buildroot.org/downloads/manual/manual.html#requirement-mandatory) installed.

**Comment by namjaejeon** [comment] 2020-05-05 13:46
@jameshilliard Is there any way to build only exfatprogs ? "make" command seems to build all packages.

**Comment by jameshilliard** [comment] 2020-05-05 16:34
> Is there any way to build only exfatprogs ?

`make exfatprogs` I think should work

**Comment by namjaejeon** [comment] 2020-05-12 21:20
@jameshilliard issues you raise seems to be clear. Could you please confirm it with exfatprogs-1.0.3 ?

**Comment by jameshilliard** [comment] 2020-05-15 20:43
@namjaejeon Package has just been bumped in buildroot, so far no [autobuilder failures with exfatprogs-1.0.3](http://autobuild.buildroot.net/?reason=exfatprogs-1.0.3) but it was just bumped so could take some time to show up if there's anything that was missed.

**Comment by namjaejeon** [comment] 2020-05-16 07:49
@jameshilliard okay!

**Closed** 2020-05-16 21:05 UTC
